version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: database
    ports:
      - "2222:2222"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:1493/customers
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=tuchkaponi
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "1493:1493"
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tuchkaponi